package com.example.demo.controller.object;

public enum ErrorCode {
    DEFAULT_ERROR, NOT_AUTHENTICATED, NOT_AUTHORIZED, BAD_REQUEST, NOT_FOUND, USER_ALREADY_EXIST, PASSWORDS_NOT_MATCH, PASSWORD_NOT_MATCH_REGEX,
    EMAIL_NOT_MATCH_REGEX, USERNAME_TOO_SHORT, USERNAME_TOO_LONG, KEY_NOT_FOUND, KEY_EXPIRED, ACCOUNT_NOT_ACTIVATED, INVALID_CREDENTIALS, EMAIL_ALREADY_EXIST
}
